Fix "AttributeError: module 'collections' has no attribute 'Mapping'"
Mapping is no longer accesible through `collections.Mapping`. It was
deprecated in python 3.8.

I have added the import as `from collections.abc import Mapping`, and
then using directly `Mapping` in line 44 (now 46) of client.py
`class Servers(Mapping)`.